In [2]:
import numpy as np
import random
from time import sleep

# Function to create a 3x3 tic-tac-toe board
def create_board():
    return np.zeros((3, 3), dtype=int)

# Function to get all available positions
def possibilities(board):
    return [(i, j) for i in range(3) for j in range(3) if board[i, j] == 0]

# Function to randomly place a player's move
def random_place(board, player):
    selection = possibilities(board)
    if selection:
        current_loc = random.choice(selection)
        board[current_loc] = player
    return board

# Function to check if a player has won
def check_win(board, player):
    return (
        any(np.all(board == player, axis=0)) or  # Check rows
        any(np.all(board == player, axis=1)) or  # Check columns
        np.all(np.diag(board) == player) or      # Check main diagonal
        np.all(np.diag(np.fliplr(board)) == player)  # Check secondary diagonal
    )

# Function to evaluate the board and determine the game result
def evaluate(board):
    for player in [1, 2]:
        if check_win(board, player):
            return player  # Return the winning player
    return -1 if np.all(board != 0) else 0  # Return -1 for draw, 0 for ongoing

# Main function to play the game
def play_game():
    board = create_board()
    winner = 0
    counter = 1

    print("Initial Board:\n", board)
    sleep(1)

    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print(f"\nBoard after {counter} move:")
            print(board)
            sleep(1)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break

    print("\nFinal Board:\n", board)
    return f"Winner is: {winner}" if winner > 0 else "It's a Draw!"

# Driver Code
if __name__ == "__main__":
    print(play_game())


Initial Board:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Board after 1 move:
[[0 0 0]
 [0 0 0]
 [1 0 0]]

Board after 2 move:
[[2 0 0]
 [0 0 0]
 [1 0 0]]

Board after 3 move:
[[2 0 0]
 [0 0 1]
 [1 0 0]]

Board after 4 move:
[[2 0 0]
 [2 0 1]
 [1 0 0]]

Board after 5 move:
[[2 0 0]
 [2 1 1]
 [1 0 0]]

Board after 6 move:
[[2 2 0]
 [2 1 1]
 [1 0 0]]

Board after 7 move:
[[2 2 1]
 [2 1 1]
 [1 0 0]]

Final Board:
 [[2 2 1]
 [2 1 1]
 [1 0 0]]
Winner is: 1
